apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 1  # Change replicas in overlay
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:alpine  # Different image
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: app-config  # Will auto-resolve to app-config-<hash>
              key: ENVIRONMENT
