# Replace ingress
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-api
  namespace: stage
spec:
  gatewayClassName: nginx-gateway-class
  listeners:
  - name: api-https
    protocol: HTTPS
    port: 443
    hostname: k8s.dev
    tls:
      certificateRefs:
      - kind: Secret
        group: ""
        name: tls-k8s-dev

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-route
  namespace: stage
spec:
  parentRefs:
  - name: tls-api
  hostnames:
  - "k8s.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: api
      port: 80
